Add ability to assign evaluators to learning objects
Cyber4All/user-service pull request #199
Opened 2021-08-27 20:31 UTC by Cwagne17

PR partially completes [Story 5141](https://app.clubhouse.io/clarkcan/story/5141/add-ability-to-assign-evaluators-to-learning-objects). 

Adds the route /users/:userId to return a user via id

2021-08-30 11:31 UTC, pzalep1 commented on src/drivers/MockDriver.ts
> +  getUser(userId: string): Promise<User> {
Is there a test we can add for this new function? I am not sure what the state of user service testing is.

2021-08-30 12:32 UTC, mfranz1 commented on src/drivers/MongoDriver.ts
> +import { Db, ObjectId, ObjectID } from 'mongodb';
I don't think the 'ObjectId' import is needed?

2021-08-30 13:07 UTC, EVogel1999 requested changes
This cannot be merged in until we don't have a route collision.  You. can test this by getting a user by either their id or username.

2021-08-31 16:50 UTC, EVogel1999 reviewed
Two small comments about the route.  It looks good though!

2021-08-31 16:50 UTC, EVogel1999 commented on src/UserMetaRetriever/adapters/ExpressRouterAdapter.ts
> +    if (req.params.username === 'tokens') {
This will always skip over since req.params.username does not exist, only :user.

2021-08-31 16:50 UTC, EVogel1999 commented on src/UserMetaRetriever/adapters/ExpressRouterAdapter.ts
> +    }
I think we should have a default to username instead. of throwing an error, that way it's backwards compatible with the frontend user profile and you don't have to update the client.

2021-08-31 17:34 UTC, pzalep1 commented on src/UserMetaRetriever/adapters/ExpressRouterAdapter.ts
> +    }
I agree here.

2021-08-31 18:07 UTC, Cwagne17 commented on src/UserMetaRetriever/adapters/ExpressRouterAdapter.ts
> +    }
Ok sounds good.

2021-08-31 18:13 UTC, pzalep1 approved these changes

2021-08-31 19:15 UTC, EVogel1999 approved these changes

2021-09-01 18:52 UTC, mfranz1 approved these changes

2021-09-02 15:25 UTC, EVogel1999 approved these changes
Small thing.  Looks good!

2021-09-03 13:09 UTC, Cwagne17 commented on src/interfaces/Query.ts
> +  accessGroups?: any[];
It has to be any because of the regex

2021-09-03 13:10 UTC, merged