7125/implement authentication module emails
Cyber4All/user-service pull request #214
Opened 2022-02-17 16:50 UTC by EVogel1999

# Description

This PR updates user service to use the new sendgrid IP and the new authentication emails.  It removes the mail routes which weren't being used and cleans up some of the ENVs that were redundant.  When a user resets their password, a confirmation is sent to the email.  Completes [7125/implement authentication module emails](https://app.shortcut.com/clarkcan/story/7125/implement-authentication-module-emails).

# ENVs

These ENV changes will need to be done before this PR is merged in.  It also needs to be done locally in the clark-environments repo.

## To Add

GATEWAY_API
USERS_API

## To Change

SENDGRID_API_KEY

## To Delete

EMAIL_VERIFIED_REDIRECT

2022-02-17 17:12 UTC, JosueMolinaMorales reviewed
Just one comment

2022-02-17 17:26 UTC, StarChaser44 commented on src/interactors/MailerInteractor.ts
> +   * @param responder The http responder
+1

2022-02-17 17:27 UTC, StarChaser44 commented on src/interactors/MailerInteractor.ts
>      responder: Responder
missing responder in block comment

2022-02-17 17:28 UTC, StarChaser44 commented on src/interactors/MailerInteractor.ts
>      responder: Responder
missing responder in block comment

2022-02-17 17:30 UTC, StarChaser44 commented on src/interactors/MailerInteractor.ts
>  import * as MAIL_DEFAULTS from '../interfaces/Mailer.defaults';
This import goes at the top

2022-02-17 17:38 UTC, StarChaser44 requested changes
Just some user service standards

2022-02-17 20:15 UTC, pzalep1 reviewed
Looks good! Just the one question.

2022-02-17 20:15 UTC, pzalep1 commented on src/environment/routes.ts
> +    return `${process.env.AUTH_REDIRECT}/reset-password?otaCode=${otaCode}`;
Out of curiosity, why was this not here before?

2022-02-18 13:44 UTC, StarChaser44 approved these changes

2022-02-18 14:29 UTC, EVogel1999 commented on src/environment/routes.ts
> +    return `${process.env.AUTH_REDIRECT}/reset-password?otaCode=${otaCode}`;
I have no clue.  When I got the email locally it wouldn't open to the correct page.  It probably wasn't an issue in prod because the URL was the other ENV that will be removed.

2022-02-21 13:28 UTC, JosueMolinaMorales approved these changes

2022-02-21 14:19 UTC, mfranz1 approved these changes

2022-02-21 21:44 UTC, pzalep1 approved these changes

2022-02-22 16:56 UTC, merged